---
title: "project_insruance_store"
author: "ShanZhong"
date: "2019/7/9"
output: pdf_document
---

# 需要设置anaconda路径
# 需要设置wd路径
```{r library, include=FALSE}

wd<-"E:/insurance"

#检查并安装package
packages.used <- c("stringr","data.table","xlsx","reticulate","cluster")

# check packages that need to be installed.
packages.needed <- setdiff(packages.used, intersect(installed.packages()[,1], packages.used))

# install additional packages
if(length(packages.needed) > 0) {
  install.packages(packages.needed, dependencies = TRUE, repos = 'http://cran.us.r-project.org')
}

library("data.table");library("stringr");library("xlsx");library("reticulate");library("cluster")

# 找到Anaconda3 路径
use_condaenv("C:/Users/zhong/Anaconda3")
# 引入钟山语言分析包
source(paste0(wd,"/shan_cn_language_packages/shan_stringr/shan_stringr_functions.R",sep=""), encoding = "utf-8")
# 引入python下载器与文件处理器
source_python("./library/downloader.py")
source_python("./library/shan_file_processor.py")
source("./library/shan_file_processor.R")
# 引入python os包
os <- import('os')

urllib <- import("urllib")

```


# 第一步,将scrapy抓取的文件转移到project_insurance_store下
# build in python
```{r movefile}

wd1<-shan_str_replace_all("[/]","\\\\",wd)

path_in <- paste0(wd1,"\\project_insurance_scrap\\output")
path_out <- paste0(wd1,"\\project_insurance_store\\input_new\\")

shan_move_file(path_in,path_out)

```

# 第二步,读取所有的保险公司文件总结，并储存为dat

```{r summarizefile}

dat<-shan_read_dir_csv(path_out)

saveRDS(dat, "./input_old/output.rds")

dat
```

# 第三步,分各个公司下载所有的保险条款

```{r summarizefile}


```



